num_gpus: 4
train:
  enable: True
  checkpoint_metric: val/ED_step19_mean_naive
  checkpoint_mode: min
  batch_size: 32
val:
  batch_size: 32
test:
  enable: False
solver:
  num_epochs: 30
  warmup_epochs: 4
  lr: 5e-4
  weight_decay: 1e-3
  warmup_epochs: 3
data:
  train_anno_path: data/ego4d/annotations/fho_lta_train.json
  val_anno_path: data/ego4d/annotations/fho_lta_val.json
  test_anno_path: data/ego4d/annotations/fho_lta_test_unannotated.json
  output_segments: [0, 20]
  input_segments: [-8, 0]
  input_from_annotated_segments: True
  use_gt_text: True
  prediction_path: data/recognition/ego4dv1/val/submit.json
model:
  base_feat_size: 512
  text_feat_size: 256
  pte:
    num_layers: 1
    num_heads: 8
    enc_dropout: 0.1
    pos_dropout: 0.5
  num_actions_to_predict: 20
  total_actions_to_predict: 20
  loss_wts_heads: [1., 1.]
  loss_wts_temporal: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]